image: docker:stable

stages:
  - build
  - test

variables:
  IMAGE: registry.gitlab.com/court-room/snake_eyes

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login --username $CI_REGISTRY_USER --password $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker image build --tag $IMAGE:$CI_COMMIT_SHA .
  after_script:
    - docker image push $IMAGE:$CI_COMMIT_SHA

test:
  stage: test
  image: $IMAGE:$CI_COMMIT_SHA
  script:
    - snake_eyes lint --skip-init /snake_eyes
