version: "3.8"


networks:
  email:
    name: email_service_email
    external: true
  website:
  website-postgres:
  website-redis:

volumes:
  postgres-data:
  redis-data:


services:
  postgres:
    image: "postgres:9.5"
    networks:
      - website-postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "snake_eyes"
      POSTGRES_PASSWORD: "devpassword"

  redis:
    command: "redis-server --requirepass devpassword"
    image: "redis:3.0-alpine"
    networks:
      - website-redis
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"

  website:
    image: "website"
    command: "gunicorn --config 'python:config.gunicorn' --reload snake_eyes.app:create_app()"
    networks:
      - website
      - website-redis
      - website-postgres
    volumes:
      - ".:/snake_eyes"
    ports:
      - "8000:8000"
    build:
      context: "."
    env_file: .env
    environment:
      APP_TYPE: web

  celery:
    image: "celery"
    command: "celery worker --beat --app snake_eyes.blueprints.contact.tasks --loglevel info"
    networks:
      - email
      - website
      - website-postgres
      - website-redis
    volumes:
      - ".:/snake_eyes"
    build:
      context: "."
    env_file: .env
    environment:
      APP_TYPE: worker
