version: "3.8"

networks:
  snake_eyes:
    driver: bridge
    name: snake_eyes

services:
  celery:
    command: "celery worker -l info -A snake_eyes.blueprints.contact.tasks"
    networks:
      - snake_eyes
    volumes:
      - ".:/snake_eyes"
      - "./instance:/snake_eyes/instance"
    build:
      context: "."
      dockerfile: "Dockerfile"

  redis:
    command: "redis-server --requirepass devpassword"
    image: "redis:6.2.1-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"

  snake_eyes:
    command: "gunicorn --bind 0.0.0.0:8000 --access-logfile - --reload snake_eyes.app:create_app()"
    networks:
      - snake_eyes
    volumes:
      - ".:/snake_eyes"
      - "./instance:/snake_eyes/instance"
    ports:
      - "8000:8000"
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      PYTHONUNBUFFERRED: "true"

volumes:
  redis-data:
