version: "2"


volumes:
  postgres-data:
  redis-data:


services:
  postgres:
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "snake_eyes"
      POSTGRES_PASSWORD: "devpassword"

  redis:
    command: "redis-server --requirepass devpassword"
    image: "redis:3.0-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"

  website:
    image: "website"
    command: "gunicorn --config 'python:config.gunicorn' --reload snake_eyes.app:create_app()"
    volumes:
      - ".:/snake_eyes"
      - "./instance:/snake_eyes/instance"
    ports:
      - "8000:8000"
    build:
      context: "."
      dockerfile: "backend.Dockerfile"
    environment:
      PYTHONUNBUFFERED: "true"

  celery:
    image: "celery"
    command: "celery worker --beat --app snake_eyes.blueprints.contact.tasks --loglevel info"
    volumes:
      - ".:/snake_eyes"
      - "./instance:/snake_eyes/instance"
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      PYTHONUNBUFFERED: "true"
