name: "deploy"

on:
  push:
    branch: ["master"]

jobs:
  deploy:
    needs: build
    runs-on: "ubuntu-latest"
    if: github.event_name == "push"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Deploy the web app"
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: snake-eyes-web
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true

      - name: "Deploy the worker app"
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: worker
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: snake-eyes-worker
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true