name: "Pipeline"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# env:
#   BACKEND_IMAGE_NAME_HEROKU_REGISTRY: registry.heroku.com/snake-eyes-backend/web
#   WORKER_IMAGE_NAME_HEROKU_REGISTRY: registry.heroku.com/snake-eyes-worker/web

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login the github docker container registry"
        uses: "docker/login-action@v1"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: "Build and push the Docker image"
      #   id: docker_build
      #   uses: "docker/build-push-action@v2"
      #   with:
      #     push: true
      #     tags: onlinejudge95/snake_eyes/snake_eyes:$GITHUB_SHA

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

  #     - name: "Build the Docker image"
  #       run: |
  #         docker image build --file Dockerfile --tag $IMAGE_NAME_GITHUB_REGISTRY:$GITHUB_SHA .
  #         docker image push $IMAGE_NAME_GITHUB_REGISTRY:$GITHUB_SHA

  # push:
  #   needs: build
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: "actions/checkout@v2"

  #     - name: "Pull the current docker image for backend and worker"
  #       run: |
  #         echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin docker.pkg.github.com
  #         docker image pull $IMAGE_NAME_GITHUB_REGISTRY:$GITHUB_SHA

  #     - name: "Login the heroku docker registry"
  #       run: docker login --username _ --password ${{ secrets.HEROKU_AUTH_TOKEN }} registry.heroku.com

  #     - name: "Tag and Push the Docker image for backend"
  #       run: |
  #         docker image tag $IMAGE_NAME_GITHUB_REGISTRY:$GITHUB_SHA $BACKEND_IMAGE_NAME_HEROKU_REGISTRY:$GITHUB_SHA
  #         docker image push $BACKEND_IMAGE_NAME_HEROKU_REGISTRY:$GITHUB_SHA

  #     - name: "Tag Push the Docker image for worker"
  #       run: |
  #         docker image tag $IMAGE_NAME_GITHUB_REGISTRY:$GITHUB_SHA $WORKER_IMAGE_NAME_HEROKU_REGISTRY:$GITHUB_SHA
  #         docker image push $WORKER_IMAGE_NAME_HEROKU_REGISTRY:$GITHUB_SHA
