name: "Pipeline"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BACKEND_IMAGE_NAME: docker.pkg.github.com/onlinejudge95/snake_eyes/snake_eyes_backend
  # WORKER_IMAGE_NAME: docker.pkg.github.com/onlinejudge95/snake_eyes_worker

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"

    - name: "Login the docker registry"
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin docker.pkg.github.com

    - name: "Build and push the Docker image for backend"
      run: |
        VERSION=$(date +%Y-%m-%d-%H-%M)
        docker image build --file Dockerfile --tag $BACKEND_IMAGE_NAME:$VERSION .

        docker image push $BACKEND_IMAGE_NAME:$VERSION
