name: "pipeline"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login the github docker container registry"
        uses: "docker/login-action@v1"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Docker meta info for tag managements"
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: onlinejudge95/snake_eyes
          tags: type=sha

      - name: "Build and push the Docker image"
        id: docker_build
        uses: "docker/build-push-action@v2"
        with:
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: "Image digest"
        run: echo ${{ steps.docker_build.outputs.digest }}

  # deploy:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: "actions/checkout@v2"
# https://github.com/marketplace/actions/deploy-to-heroku#deploy-with-docker